Models/ErrorViewModel.cs
namespace ASP.NET_PA1._2_z3_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Miasto.cs
using System.ComponentModel.DataAnnotations;

namespace ASP.NET_PA1._2_z3_MVC.Models
{
    public class Miasto
    {
        public int Id { get; set; }
        public string? Nazwa { get; set; }

        public uint? Populacja { get; set; }
        public decimal? Powierzchnia { get; set; }

        [DataType(DataType.Date)]
        public DateTime DataZałożenia { get; set; }
        public string Województwo { get; set; }
    }
}

ViewModels/HomeTestViewmodel.cs
namespace ASP.NET_PA1._2_z3_MVC.ViewModels
{
    public class HomeTestViewmodel
    {
        public int? Id { get; set; }
        public string? Imię { get; set; }
    }
}

Controllers/HomeController.cs
using ASP.NET_PA1._2_z3_MVC.Models;
using ASP.NET_PA1._2_z3_MVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;


namespace ASP.NET_PA1._2_z3_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test(
            string imię,
            int? id = 0
            )
        {
            //ViewData["Imię"] = imię;
            //ViewBag.Id = id;
            return View(
                new HomeTestViewmodel()
                {
                    Id = id,
                    Imię = imię
                }
                );
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel {
                    RequestId = Activity.Current?.Id
                    ?? HttpContext.TraceIdentifier
                    }
                );
        }
    }
}

Controllers/MiastaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP.NET_PA1._2_z3_MVC.Data;
using ASP.NET_PA1._2_z3_MVC.Models;

namespace ASP.NET_PA1._2_z3_MVC.Controllers
{
    public class MiastaController : Controller
    {
        private readonly DataContext _context;

        public MiastaController(DataContext context)
        {
            _context = context;
        }

        // GET: Miasta
        public async Task<IActionResult> Index()
        {
              return View(await _context.Miasta.ToListAsync());
        }

        // GET: Miasta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miasto == null)
            {
                return NotFound();
            }

            return View(miasto);
        }

        // GET: Miasta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Miasta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Nazwa,Populacja,Powierzchnia,DataZałożenia,Województwo")] Miasto miasto
            )
        {
            if (ModelState.IsValid)
            {
                _context.Add(miasto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(miasto);
        }

        // GET: Miasta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta.FindAsync(id);
            if (miasto == null)
            {
                return NotFound();
            }
            return View(miasto);
        }

        // POST: Miasta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("Id,Nazwa,Populacja,Powierzchnia,DataZałożenia,Województwo")] Miasto miasto
            )
        {
            if (id != miasto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(miasto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MiastoExists(miasto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(miasto);
        }

        // GET: Miasta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Miasta == null)
            {
                return NotFound();
            }

            var miasto = await _context.Miasta
                .FirstOrDefaultAsync(m => m.Id == id);
            if (miasto == null)
            {
                return NotFound();
            }

            return View(miasto);
        }

        // POST: Miasta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Miasta == null)
            {
                return Problem("Entity set 'DataContext.Miasto'  is null.");
            }
            var miasto = await _context.Miasta.FindAsync(id);
            if (miasto != null)
            {
                _context.Miasta.Remove(miasto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MiastoExists(int id)
        {
          return _context.Miasta.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Test.cshtml
@model ASP.NET_PA1._2_z3_MVC.ViewModels.HomeTestViewmodel;

@{
    ViewData["Title"] = "Test";
}
<h1>Test</h1>

@for (int i = 0; i < Model.Id; i++) {
    <p>Otrzymałem imię: @Model.Imię</p>
}

Views/Miasta/Create.cshtml
@model ASP.NET_PA1._2_z3_MVC.Models.Miasto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Miasto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacja" class="control-label"></label>
                <input asp-for="Populacja" class="form-control" />
                <span asp-validation-for="Populacja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Powierzchnia" class="control-label"></label>
                <input asp-for="Powierzchnia" class="form-control" />
                <span asp-validation-for="Powierzchnia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZałożenia" class="control-label"></label>
                <input asp-for="DataZałożenia" class="form-control" />
                <span asp-validation-for="DataZałożenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Województwo" class="control-label"></label>
                <input asp-for="Województwo" class="form-control" />
                <span asp-validation-for="Województwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Miasta/Delete.cshtml
@model ASP.NET_PA1._2_z3_MVC.Models.Miasto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Miasto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Populacja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Populacja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Powierzchnia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Powierzchnia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZałożenia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZałożenia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Województwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Województwo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Miasta/Details.cshtml
@model ASP.NET_PA1._2_z3_MVC.Models.Miasto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Miasto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Populacja)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Populacja)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Powierzchnia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Powierzchnia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataZałożenia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataZałożenia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Województwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Województwo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Miasta/Edit.cshtml
@model ASP.NET_PA1._2_z3_MVC.Models.Miasto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Miasto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" />
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Populacja" class="control-label"></label>
                <input asp-for="Populacja" class="form-control" />
                <span asp-validation-for="Populacja" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Powierzchnia" class="control-label"></label>
                <input asp-for="Powierzchnia" class="form-control" />
                <span asp-validation-for="Powierzchnia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataZałożenia" class="control-label"></label>
                <input asp-for="DataZałożenia" class="form-control" />
                <span asp-validation-for="DataZałożenia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Województwo" class="control-label"></label>
                <input asp-for="Województwo" class="form-control" />
                <span asp-validation-for="Województwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Miasta/Index.cshtml
@model IEnumerable<ASP.NET_PA1._2_z3_MVC.Models.Miasto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nazwa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Populacja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Powierzchnia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataZałożenia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Województwo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Populacja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Powierzchnia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataZałożenia)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Województwo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_PA1._2_z3_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_PA1._2_z3_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET_PA1._2_z3_MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a
                                class="nav-link text-dark"
                                asp-area=""
                                asp-controller="Home"
                                asp-action="Index"
                            >Home</a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link text-dark"
                                asp-area=""
                                asp-controller="Home"
                                asp-action="Test"
                            >Test</a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link text-dark"
                                asp-area=""
                                asp-controller="Miasta"
                                asp-action="Index"
                            >Miasta</a>
                        </li>
                        <li class="nav-item">
                            <a
                                class="nav-link text-dark"
                                asp-area=""
                                asp-controller="Home"
                                asp-action="Privacy"
                            >Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASP.NET_PA1._2_z3_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>